name: Auto Update Coupons

on:
  schedule:
    - cron: "0 9 * * *"  # every day at 9 AM UTC
  workflow_dispatch:      # allows manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update script
        run: |
          python update_coupons.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add coupons.json || echo "No file changes to stage"
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "🤖 Auto-update coupons.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
